apiVersion: v1
kind: Service
metadata:
  name: snake-game-service
spec:
  type: NodePort
  selector:
    app: snake-game
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007apiVersion: v1
kind: Service
metadata:
  name: snake-game-service
spec:
  type: NodePort
  selector:
    app: snake-game
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
